server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: 135321
    url: jdbc:mysql://localhost:3306/zsgcdemoself?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
